name: ${project_name}
services:
    workspace:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace
            - ~/.ssh:/root/.ssh
            - ./nginx:/etc/nginx
        env_file:
            - path: ./.env
              required: true
            - path: ./override.env
              required: false

    postgres:
        container_name: sso-postgres
        image: postgres:17.0-bullseye
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - path: "./postgres/.default_db_config.env"
              required: true
            - path: "./postgres/.override_db_config.env"
              required: false
            - path: ./.env
              required: true
            - path: ./override.env
              required: false
        networks:
            - dev-net

networks:
    dev-net:
        external: true

volumes:
    postgres:
